name: AGENCIAS

on:
    push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Process running
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

        python servidor.py
